services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  setup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA:-public}
      CSV_URL: ${CSV_URL}
    command: ["scripts/wait_for_db.sh", "python", "-m", "initial_setup.setup_database"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - setup
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CSV_URL: ${CSV_URL}
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
    volumes:
      - .:/app
    expose:
      - "5000"
    command: ["python", "app.py"]

volumes:
  pgdata: